# Основной конфигурационный файл ADB Блюстакс Автоматизация
# Все пути указаны относительно корневой папки проекта

# Настройки ADB
adb:
  # Путь к исполняемому файлу ADB (оставьте пустым для использования системного)
  path: ""
  # Порт для ADB сервера
  port: 5037
  # Время ожидания для ADB-команд в секундах
  timeout: 10
  # Максимальное количество повторных попыток для ADB-команд
  max_retries: 3
  # Интервал между повторными попытками в секундах
  retry_interval: 2

# Настройки устройств
devices:
  # Файл со списком устройств (формат: IP:порт:название или IP:порт)
  devices_file: "configs/devices.txt"
  # Размер пакета для параллельной обработки устройств
  batch_size: 10
  # Задержка между запуском потоков в секундах
  thread_delay: 1
  # Таймаут подключения к устройству в секундах
  connect_timeout: 15
  # Автоматическое переподключение к устройствам
  auto_reconnect: true
  # Интервал проверки состояния устройств в секундах
  status_check_interval: 60

# Настройки выполнения
execution:
  # Интервал между действиями в миллисекундах
  action_interval: 500
  # Максимальное количество попыток для каждого действия
  max_action_attempts: 5
  # Пауза между попытками в миллисекундах
  retry_delay: 2000
  # Время ожидания после каждого клика в миллисекундах
  click_delay: 1000
  # Порог совпадения изображений (от 0.0 до 1.0)
  image_match_threshold: 0.7
  # Максимальное время ожидания появления изображения в секундах
  wait_timeout: 30

# Настройки планировщика
scheduler:
  # Включить автоматический запуск по расписанию
  enabled: true
  # Минуты для запуска (каждый час)
  run_minutes: [5, 25, 45]
  # Максимальное количество одновременно запущенных потоков
  max_threads: 20
  # Запуск немедленно после старта программы
  run_on_start: true

# Настройки журнала
logging:
  # Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Каталог для файлов журнала
  directory: "logs"
  # Формат файла журнала
  file_format: "{date}_{device}.log"
  # Максимальный размер файла журнала в байтах (по умолчанию 10 МБ)
  max_size: 10485760
  # Количество файлов журнала для ротации
  backup_count: 5
  # Включить цветной вывод в консоль
  colored_console: true

# Пути к каталогам
directories:
  # Каталог с шаблонами изображений
  templates: "screenshots/templates"
  # Каталог для выходных изображений
  output: "screenshots/output"
  # Каталог с конфигурациями
  configs: "configs"
  # Каталог для временных файлов
  temp: "temp"

# Настройки интеграций
integrations:
  # Интеграция с Telegram
  telegram:
    enabled: false
    token: ""
    chat_ids: []
    # Интервал уведомлений в секундах
    notification_interval: 300
    # Отправлять скриншоты
    send_screenshots: true
    # Команды, на которые бот будет реагировать
    commands:
      - start
      - status
      - stop
      - restart
      - screenshot

  # Интеграция с Google Sheets
  google_sheets:
    enabled: false
    # Путь к файлу учетных данных сервисного аккаунта
    credentials_file: "credentials.json"
    # ID таблицы
    spreadsheet_id: ""
    # Лист для записи результатов
    sheet_name: "Результаты"
    # Интервал обновления в секундах
    update_interval: 300

  # Интеграция с API для распознавания изображений (OpenAI)
  openai:
    enabled: false
    api_key: ""
    model: "gpt-4"
    # Максимальное количество запросов в минуту
    rate_limit: 10

# Настройки пользовательского интерфейса
ui:
  # Стиль отображения текста (simple, rich)
  style: "rich"
  # Показывать прогресс-бар для каждого устройства
  show_progress: true
  # Интервал обновления интерфейса в миллисекундах
  update_interval: 100
  # Максимальное количество строк в консоли
  max_lines: 50
  # Отображать системные сообщения
  show_system_messages: true

# Настройки отладки
debug:
  # Включить режим отладки
  enabled: false
  # Сохранять все скриншоты в процессе выполнения
  save_all_screenshots: false
  # Отображать все команды ADB
  show_adb_commands: false
  # Замедление выполнения для отладки (множитель)
  slowdown_factor: 1.0